site_name: WOUDC Guides
site_url: http://docs.woudc.org
repo_url: https://github.com/woudc/woudc-guidebook

#site_dir: 'site_bootstrap'
#theme_dir: 'bootstrap_theme'
#theme: bootstrap

theme_dir: 'woudc_theme'
site_dir: 'site_woudc'

markdown_extensions:
    - admonition
    - meta
    - toc:
        anchorlink: True
#        permalink: True
#        baselevel: 2

pages:
- Contributor Guide: 'contributor-guide-en.md'
- Guide du contributeur: 'contributor-guide-fr.md'
extra:
    version: 1.0