site_name: WOUDC Contributor Guide
site_url: http://guide.woudc.org
repo_url: https://github.com/woudc/woudc-guidebook

theme_dir: 'woudc_theme'

markdown_extensions:
    - admonition
    - meta
    - toc:
        anchorlink: True
#        permalink: True
#        baselevel: 2

pages:
- Contributor Guide: 'index.md'
- Guide du contributeur: 'index-fr.md'

extra:
    version: 1.0
