site_name: Contributor Guide
site_url: http://docs.woudc.org
repo_url: https://github.com/woudc/woudc-guidebook
theme_dir: 'woudc_theme'
markdown_extensions:
    - admonition
    - meta
    - toc:
        anchorlink: True
#        permalink: True
#        baselevel: 2

pages:
- Contributor Guide: 'contributor-guide-en.md'
- Guide du contributeur: 'contributor-guide-fr.md'
